APP_NAME = "Genis Email Hub"
GRAPH_BASE = "https://graph.microsoft.com/v1.0"
SCOPES = ["Mail.Read", "Mail.Send", "Mail.ReadWrite", "User.Read"]
DEFAULT_CLIENT_ID = "14d82eec-204b-4c2f-b7e8-296a70dab67e"
AUTHORITY = "https://login.microsoftonline.com/common"
POLL_INTERVAL_MS = 30000
HTTP_CONNECT_TIMEOUT_SEC = 10
HTTP_READ_TIMEOUT_SEC = 45
HTTP_GET_RETRIES = 1
BROWSER_RUNTIME_INSTALL_URL = "https://go.microsoft.com/fwlink/p/?LinkId=2124703"

BYTES_PER_KB = 1024
BYTES_PER_MB = 1024 * 1024

INCHES_PER_FOOT = 12.0
MM_PER_INCH = 25.4
CM_PER_INCH = 2.54
INCHES_PER_METER = 39.37007874015748

TAKEOFF_DOOR_ESTIMATE_LINEAR_FEET = 42.0
TAKEOFF_DEFAULT_DOOR_WIDTH_FEET = 3.0
TAKEOFF_DEFAULT_DOOR_HEIGHT_FEET = 6.6667
TAKEOFF_DEFAULT_COATS = 1
TAKEOFF_OPENING_RECT_FIELD_COUNT = 4
TAKEOFF_DEFAULT_WALL_HEIGHT = "8ft"

QT_WINDOW_DEFAULT_GEOMETRY = "1280x820"
QT_WINDOW_MIN_WIDTH = 1000
QT_WINDOW_MIN_HEIGHT = 680
QT_SPLITTER_LEFT_DEFAULT = 300
QT_SPLITTER_RIGHT_DEFAULT = 1120
QT_THREAD_POOL_MAX_WORKERS = 3
INTERNET_DEFAULT_URL = "https://www.bing.com"

EMAIL_DELTA_FALLBACK_TOP = 20
EMAIL_LIST_FETCH_TOP = 1000
EMAIL_COMPANY_FETCH_PER_FOLDER = 1000
EMAIL_COMPANY_CACHE_TTL_SEC = 120
EMAIL_COMPANY_MEMORY_CACHE_MAX = 20
TOKEN_CACHE_ID_HASH_CHARS = 12
SQL_PARAM_CHUNK_SIZE = 900

FOLDER_DISPLAY = {
    "inbox": "Inbox",
    "sentitems": "Sent",
    "drafts": "Drafts",
    "archive": "Archive",
    "deleteditems": "Deleted",
    "junkemail": "Junk",
}
